// <auto-generated />
namespace WebApplication_LibraryManagementProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Version12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version12));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020755228_Version1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
